name = "holila-catalog-worker"
main = "src/index.ts"
compatibility_date = "2025-08-05"
compatibility_flags = ["nodejs_compat"]

secrets_store_secrets = [
  { binding = "API_SECRET_TOKEN", store_id = "abb00fb0ccf54bb494eea71e71a1324f", secret_name = "HOLILA_WORKER_TOKEN" },
]

[[d1_databases]]
binding = "DB"
database_name = "holila-catalog"
database_id = "54f15ed1-5127-4b3d-a4e2-e15fe33bd587"

[observability.logs]
enabled = true

[vars]
ALLOWED_ORIGINS = "holila://app,http://localhost:3000,http://localhost:8787"
