name = "holila-catalog-worker"
main = "src/index.ts"
compatibility_date = "2025-08-05"
compatibility_flags = ["nodejs_compat"]

secrets_store_secrets = [
  { binding = "API_SECRET_TOKEN", store_id = "d94892f45f8d4a5d8e1c1152c1eda649", secret_name = "HOLILA_WORKER_TOKEN" },
]

[[d1_databases]]
binding = "DB"
database_name = "holila-catalog"
database_id = "538357d7-85fe-4522-b4b3-db0ef90d9af2"

[observability.logs]
enabled = true

[vars]
ALLOWED_ORIGINS = "holila://app,http://localhost:3000,http://localhost:8787"
